version: '3.7'
services:
  vpn-server:
    image: lscr.io/linuxserver/wireguard:alpine
    container_name: wireguard-server
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE # Required for kernels below 5.6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi #set correct timezone
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - ALLOWEDIPS=0.0.0.0/0 #Peer addresses allowed
      - INTERNAL_SUBNET=172.66.66.0 #Subnet used in VPN tunnel
      - SERVERURL=auto # Auto detect external IP
    volumes:
      - ./config:/config
      # - /usr/src:/usr/src # Required for kernels below 5.6. Location of kernel headers 
      # - /lib/modules:/lib/modules # Required for kernels below 5.6
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
